meta_product_name: "StudyTheWrd"
meta_title: "StudyTheWrd - learn the science behind the street"
meta_description: "This is you working with Grammy award winners. #TheWrd is a new school. We bring together expert educators, creative industry big hitters and deep-learning AI, to give all students the capabilities, qualifications and connections needed to pursue their preferred path in the music industry - whether that’s skilled employment, further study or a higher apprenticeship."
meta_image: "THE-WRD-5.jpg"
twitter_account: "@sharethewrd"
